<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<title>Qk4req К| анал</title>
		{{ include('favicon.phtml') }}
		<meta name="description" content="Latest updates and statistic charts">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700|Nunito:300,400,500">
		{{ assetter.css()|raw }}
	</head>
	<body style="background-image: url(/assets/themes/master/images/bg.jpg)" class="kt-quick-panel--right kt-demo-panel--right kt-offcanvas-panel--right kt-header--fixed kt-header-mobile--fixed kt-subheader--enabled kt-subheader--transparent kt-page--loading">
		<div id="kt_header_mobile" class="kt-header-mobile	kt-header-mobile--fixed">
			<div class="kt-header-mobile__logo">
				<a href="index-2.html">
				<img alt="Logo" src="../../themes/metronic/theme/default/demo8/dist/assets/media/logos/logo-8-sm.png" />
				</a>
			</div>
			<div class="kt-header-mobile__toolbar">
				<button class="kt-header-mobile__toolbar-toggler" id="kt_header_mobile_toggler"><span></span></button>
				<button class="kt-header-mobile__toolbar-topbar-toggler" id="kt_header_mobile_topbar_toggler"><i class="flaticon-more-1"></i></button>
			</div>
		</div>
		<div class="kt-grid kt-grid--hor kt-grid--root">
			<div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--ver kt-page">
				<div class="kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor kt-wrapper" id="kt_wrapper">
					<div id="kt_header" class="kt-header kt-grid__item	kt-header--fixed " data-ktheader-minimize="on">
						<div class="kt-header__top">
							<div class="kt-container	kt-container--fluid ">
								<div class="kt-header__brand	 kt-grid__item" id="kt_header_brand">
									<div class="kt-header__brand-logo">
										<a href="index-2.html">
										<img alt="Logo" style="display: none;" src="../../themes/metronic/theme/default/demo8/dist/assets/media/logos/logo-8.png" class="kt-header__brand-logo-default"/>
										<img alt="Logo" style="display: none;" src="../../themes/metronic/theme/default/demo8/dist/assets/media/logos/logo-8-inverse.png" class="kt-header__brand-logo-sticky"/>
										</a>
									</div>
								</div>
								<div class="kt-header__topbar">
									<div class="kt-header__topbar-item" data-toggle="kt-tooltip" title="Quick panel" data-placement="top">
										<div class="kt-header__topbar-wrapper">
											<span class="kt-header__topbar-icon"><i class="la la-sign-in-alt"></i></span>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="kt-header__bottom">
							<div class="kt-container	kt-container--fluid ">
								<button class="kt-header-menu-wrapper-close" id="kt_header_menu_mobile_close_btn"><i class="la la-close"></i></button>
								<div class="kt-header-menu-wrapper" id="kt_header_menu_wrapper">
									<div id="kt_header_menu" class="kt-header-menu kt-header-menu-mobile">
										<ul class="kt-menu__nav ">
											<li class="kt-menu__item	kt-menu__item--open kt-menu__item--here kt-menu__item--submenu kt-menu__item--rel" data-ktmenu-submenu-toggle="hover" aria-haspopup="true">
												<a href="index-2.html" class="kt-menu__link kt-menu__toggle">
													<span class="kt-menu__link-text">Канал</span>
													<i class="kt-menu__hor-arrow la la-angle-down"></i>
													<i class="kt-menu__ver-arrow la la-angle-right"></i>
												</a>
												<!--<div class="kt-menu__submenu kt-menu__submenu--classic kt-menu__submenu--left">
													<ul class="kt-menu__subnav">
														<li class="kt-menu__item " aria-haspopup="true"><a href="dashboards/fluid.html" class="kt-menu__link "><i class="kt-menu__link-icon flaticon2-architecture-and-city"></i><span class="kt-menu__link-text">Fluid Width</span></a></li>
														<li class="kt-menu__item " aria-haspopup="true"><a href="dashboards/aside.html" class="kt-menu__link "><i class="kt-menu__link-icon flaticon2-crisp-icons"></i><span class="kt-menu__link-text">Aside Enabled</span></a></li>
													</ul>
												</div>-->
											</li>
										</ul>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="kt-container	kt-container--fluid	kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor kt-grid--stretch">
						<div class="kt-body kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor kt-grid--stretch" id="kt_body">
							<div class="kt-content	kt-grid__item kt-grid__item--fluid kt-grid kt-grid--hor" id="kt_content">
								<div class="kt-subheader	 kt-grid__item" id="kt_subheader">
									<div class="kt-container	kt-container--fluid ">
										<div class="kt-subheader__main">
											<!--<h3 class="kt-subheader__title">
												Канал
											</h3>-->
											<span class="kt-subheader__separator kt-hidden"></span>
											<div class="kt-subheader__breadcrumbs">
												<a href="#" class="kt-subheader__breadcrumbs-home"><i class="la la-home"></i></a>
												<span class="kt-subheader__breadcrumbs-separator"></span>
												<a href="#" class="kt-subheader__breadcrumbs-link">Канал</a>
											</div>
										</div>
									</div>
								</div>
								<div class="kt-container	kt-container--fluid	kt-grid__item kt-grid__item--fluid">
									<div class="row">
										<div class="vplayer col-md-8 mt-2">
											<!--<video
												id="broadcast"
												class="video-js vjs-fluid col-md-8"
												controls
												preload="auto"
												width="640"
												height="480"
												poster="MY_VIDEO_POSTER.jpg"
												data-setup="{}">
												<source src="/assets/media/TEST.mp4" type="video/mp4" />
												<p class="vjs-no-js">
													To view this video please enable JavaScript, and consider upgrading to a
													web browser that
													<a href="https://videojs.com/html5-video-support/" target="_blank"
														>supports HTML5 video</a
													>
												</p>
											</video>-->
											<video
												id="broadcast"
												class="video-js vjs-fluid">
												<source src="http://qk4req.ru/hls/test.m3u8" type="application/x-mpegURL">
												<p class="vjs-no-js">
													To view this video please enable JavaScript, and consider upgrading to a
													web browser that
													<a href="https://videojs.com/html5-video-support/" target="_blank"
														>supports HTML5 video</a
													>
												</p>
											</video>
										</div>
										<div class="chat col-md-4 mt-2">
											<div class="kt-grid__item kt-grid__item--fluid kt-app__content" id="kt_chat_content">
														<div class="kt-chat">
																<div class="kt-portlet kt-portlet--head-lg kt-portlet--last">
																		<div class="kt-portlet__head">
																				<div class="kt-chat__head ">
																						<div class="kt-chat__left">
																								<!--begin:: Aside Mobile Toggle -->
																								<button type="button" class="btn btn-clean btn-sm btn-icon btn-icon-md kt-hidden-desktop" id="kt_chat_aside_mobile_toggle">
																										<i class="flaticon2-open-text-book"></i>
																								</button>
																								<!--end:: Aside Mobile Toggle-->

																								<div class="dropdown dropdown-inline">
																										<button type="button" class="btn btn-clean btn-sm btn-icon btn-icon-md" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
																												<i class="flaticon-more-1"></i>
																										</button>
																										<div class="dropdown-menu dropdown-menu-fit dropdown-menu-left dropdown-menu-md">
																												<!--begin::Nav-->
																												<ul class="kt-nav">
																														<li class="kt-nav__item">
																																<a href="#" class="kt-nav__link">
																																		<i class="kt-nav__link-icon flaticon2-group"></i>
																																		<span class="kt-nav__link-text">New Group</span>
																																</a>
																														</li>
																														<li class="kt-nav__item">
																																<a href="#" class="kt-nav__link">
																																		<i class="kt-nav__link-icon flaticon2-open-text-book"></i>
																																		<span class="kt-nav__link-text">Contacts</span>
																																</a>
																														</li>
																														<li class="kt-nav__item">
																																<a href="#" class="kt-nav__link">
																																		<i class="kt-nav__link-icon flaticon2-rocket-1"></i>
																																		<span class="kt-nav__link-text">Groups</span>
																																		<span class="kt-nav__link-badge">
																																						<span class="kt-badge kt-badge--brand kt-badge--inline">new</span>
																																		</span>
																																</a>
																														</li>
																														<li class="kt-nav__item">
																																<a href="#" class="kt-nav__link">
																																		<i class="kt-nav__link-icon flaticon2-bell-2"></i>
																																		<span class="kt-nav__link-text">Calls</span>
																																</a>
																														</li>
																														<li class="kt-nav__item">
																																<a href="#" class="kt-nav__link">
																																		<i class="kt-nav__link-icon flaticon2-dashboard"></i>
																																		<span class="kt-nav__link-text">Settings</span>
																																</a>
																														</li>
																														<li class="kt-nav__separator"></li>
																														<li class="kt-nav__item">
																																<a href="#" class="kt-nav__link">
																																		<i class="kt-nav__link-icon flaticon2-protected"></i>
																																		<span class="kt-nav__link-text">Help</span>
																																</a>
																														</li>
																														<li class="kt-nav__item">
																																<a href="#" class="kt-nav__link">
																																		<i class="kt-nav__link-icon flaticon2-bell-2"></i>
																																		<span class="kt-nav__link-text">Privacy</span>
																																</a>
																														</li>
																												</ul>
																												<!--end::Nav-->
																										</div>
																								</div>
																						</div>
																						
																						<div class="kt-chat__center">
																								<div class="kt-chat__label">
																										<a href="#" class="kt-chat__title">Jason Muller</a>
																										<span class="kt-chat__status">
																												<span class="kt-badge kt-badge--dot kt-badge--success"></span> Active
																										</span>
																								</div>

																								<div class="kt-chat__pic kt-hidden">
																										<span class="kt-media kt-media--sm kt-media--circle" data-toggle="kt-tooltip" data-placement="right" title="" data-original-title="Jason Muller">															
																												<img src="/metronic/themes/metronic/theme/default/demo8/dist/assets/media/users/300_12.jpg" alt="image">
																										</span>
																										<span class="kt-media kt-media--sm kt-media--circle" data-toggle="kt-tooltip" data-placement="right" title="" data-original-title="Nick Bold">															
																												<img src="/metronic/themes/metronic/theme/default/demo8/dist/assets/media/users/300_11.jpg" alt="image">
																										</span>
																										<span class="kt-media kt-media--sm kt-media--circle" data-toggle="kt-tooltip" data-placement="right" title="" data-original-title="Milano Esco">															
																												<img src="/metronic/themes/metronic/theme/default/demo8/dist/assets/media/users/100_14.jpg" alt="image">
																										</span>
																										<span class="kt-media kt-media--sm kt-media--circle" data-toggle="kt-tooltip" data-placement="right" title="" data-original-title="Teresa Fox">															
																												<img src="/metronic/themes/metronic/theme/default/demo8/dist/assets/media/users/100_4.jpg" alt="image">
																										</span>
																								</div>
																						</div>

																						<div class="kt-chat__right">
																								<div class="dropdown dropdown-inline">
																										<button type="button" class="btn btn-clean btn-sm btn-icon btn-icon-md" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
																												<i class="flaticon2-add-1"></i>
																										</button>
																										<div class="dropdown-menu dropdown-menu-fit dropdown-menu-right dropdown-menu-md">
																												<!--begin::Nav-->
																												<ul class="kt-nav">
																														<li class="kt-nav__head">
																																Messaging
																																<i class="flaticon2-information" data-toggle="kt-tooltip" data-placement="right" title="" data-original-title="Click to learn more..."></i>
																														</li>
																														<li class="kt-nav__separator"></li>
																														<li class="kt-nav__item">
																																<a href="#" class="kt-nav__link">
																																		<i class="kt-nav__link-icon flaticon2-group"></i>
																																		<span class="kt-nav__link-text">New Group</span>
																																</a>
																														</li>
																														<li class="kt-nav__item">
																																<a href="#" class="kt-nav__link">
																																		<i class="kt-nav__link-icon flaticon2-open-text-book"></i>
																																		<span class="kt-nav__link-text">Contacts</span>
																																		<span class="kt-nav__link-badge">
																																						<span class="kt-badge kt-badge--brand	kt-badge--rounded-">5</span>
																																		</span>
																																</a>
																														</li>
																														<li class="kt-nav__item">
																																<a href="#" class="kt-nav__link">
																																		<i class="kt-nav__link-icon flaticon2-bell-2"></i>
																																		<span class="kt-nav__link-text">Calls</span>
																																</a>
																														</li>
																														<li class="kt-nav__item">
																																<a href="#" class="kt-nav__link">
																																		<i class="kt-nav__link-icon flaticon2-dashboard"></i>
																																		<span class="kt-nav__link-text">Settings</span>
																																</a>
																														</li>
																														<li class="kt-nav__item">
																																<a href="#" class="kt-nav__link">
																																		<i class="kt-nav__link-icon flaticon2-protected"></i>
																																		<span class="kt-nav__link-text">Help</span>
																																</a>
																														</li>
																														<li class="kt-nav__separator"></li>
																														<li class="kt-nav__foot">
																																<a class="btn btn-label-brand btn-bold btn-sm" href="#">Upgrade plan</a>
																																<a class="btn btn-clean btn-bold btn-sm" href="#" data-toggle="kt-tooltip" data-placement="right" title="" data-original-title="Click to learn more...">Learn more</a>
																														</li>
																												</ul>
																												<!--end::Nav-->
																										</div>
																								</div>
																						</div>
																				</div>
																		</div>

																		<div class="kt-portlet__body">
																				<div class="kt-scroll kt-scroll--pull ps ps--active-y" data-mobile-height="300" style="height: 27vh; min-height: 150px; overflow: hidden;">
																						<div class="kt-chat__messages">
																								<div class="kt-chat__message">
																										<div class="kt-chat__user">
																												<span class="kt-media kt-media--circle kt-media--sm"> 
																														<img src="/metronic/themes/metronic/theme/default/demo8/dist/assets/media/users/100_12.jpg" alt="image">
																												</span>
																												<a href="#" class="kt-chat__username">Jason Muller</a>
																												<span class="kt-chat__datetime">2 Hours</span>
																										</div>
																										<div class="kt-chat__text kt-bg-light-success">
																												How likely are you to recommend our company <br>to your friends and family?
																										</div>
																								</div>
																								<div class="kt-chat__message">
																										<div class="kt-chat__user">
																												<span class="kt-media kt-media--circle kt-media--sm"> 
																														<img src="/metronic/themes/metronic/theme/default/demo8/dist/assets/media/users/100_12.jpg" alt="image">
																												</span>
																												<a href="#" class="kt-chat__username">Jason Muller</a>
																												<span class="kt-chat__datetime">2 Hours</span>
																										</div>
																										<div class="kt-chat__text kt-bg-light-success">
																												How likely are you to recommend our company <br>to your friends and family?
																										</div>
																								</div>
																								<div class="kt-chat__message">
																										<div class="kt-chat__user">
																												<span class="kt-media kt-media--circle kt-media--sm"> 
																														<img src="/metronic/themes/metronic/theme/default/demo8/dist/assets/media/users/100_12.jpg" alt="image">
																												</span>
																												<a href="#" class="kt-chat__username">Jason Muller</a>
																												<span class="kt-chat__datetime">2 Hours</span>
																										</div>
																										<div class="kt-chat__text kt-bg-light-success">
																												How likely are you to recommend our company <br>to your friends and family?
																										</div>
																								</div>
																								<div class="kt-chat__message">
																										<div class="kt-chat__user">
																												<span class="kt-media kt-media--circle kt-media--sm"> 
																														<img src="/metronic/themes/metronic/theme/default/demo8/dist/assets/media/users/100_12.jpg" alt="image">
																												</span>
																												<a href="#" class="kt-chat__username">Jason Muller</a>
																												<span class="kt-chat__datetime">2 Hours</span>
																										</div>
																										<div class="kt-chat__text kt-bg-light-success">
																												How likely are you to recommend our company <br>to your friends and family?
																										</div>
																								</div>
																								<div class="kt-chat__message">
																										<div class="kt-chat__user">
																												<span class="kt-media kt-media--circle kt-media--sm"> 
																														<img src="/metronic/themes/metronic/theme/default/demo8/dist/assets/media/users/100_12.jpg" alt="image">
																												</span>
																												<a href="#" class="kt-chat__username">Jason Muller</a>
																												<span class="kt-chat__datetime">2 Hours</span>
																										</div>
																										<div class="kt-chat__text kt-bg-light-success">
																												How likely are you to recommend our company <br>to your friends and family?
																										</div>
																								</div>
																								<div class="kt-chat__message">
																										<div class="kt-chat__user">
																												<span class="kt-media kt-media--circle kt-media--sm"> 
																														<img src="/metronic/themes/metronic/theme/default/demo8/dist/assets/media/users/100_12.jpg" alt="image">
																												</span>
																												<a href="#" class="kt-chat__username">Jason Muller</a>
																												<span class="kt-chat__datetime">2 Hours</span>
																										</div>
																										<div class="kt-chat__text kt-bg-light-success">
																												How likely are you to recommend our company <br>to your friends and family?
																										</div>
																								</div>
																								<div class="kt-chat__message">
																										<div class="kt-chat__user">
																												<span class="kt-media kt-media--circle kt-media--sm"> 
																														<img src="/metronic/themes/metronic/theme/default/demo8/dist/assets/media/users/100_12.jpg" alt="image">
																												</span>
																												<a href="#" class="kt-chat__username">Jason Muller</a>
																												<span class="kt-chat__datetime">2 Hours</span>
																										</div>
																										<div class="kt-chat__text kt-bg-light-success">
																												How likely are you to recommend our company <br>to your friends and family?
																										</div>
																								</div>
																								<div class="kt-chat__message">
																										<div class="kt-chat__user">
																												<span class="kt-media kt-media--circle kt-media--sm"> 
																														<img src="/metronic/themes/metronic/theme/default/demo8/dist/assets/media/users/100_12.jpg" alt="image">
																												</span>
																												<a href="#" class="kt-chat__username">Jason Muller</a>
																												<span class="kt-chat__datetime">2 Hours</span>
																										</div>
																										<div class="kt-chat__text kt-bg-light-success">
																												How likely are you to recommend our company <br>to your friends and family?
																										</div>
																								</div>
																								<div class="kt-chat__message">
																										<div class="kt-chat__user">
																												<span class="kt-media kt-media--circle kt-media--sm"> 
																														<img src="/metronic/themes/metronic/theme/default/demo8/dist/assets/media/users/100_12.jpg" alt="image">
																												</span>
																												<a href="#" class="kt-chat__username">Jason Muller</a>
																												<span class="kt-chat__datetime">2 Hours</span>
																										</div>
																										<div class="kt-chat__text kt-bg-light-success">
																												How likely are you to recommend our company <br>to your friends and family?
																										</div>
																								</div>
																								<div class="kt-chat__message kt-chat__message--right">
																										<div class="kt-chat__user">
																												<span class="kt-chat__datetime">30 Seconds</span>
																												<a href="#" class="kt-chat__username">You</a>
																												<span class="kt-media kt-media--circle kt-media--sm"> 
																														<img src="/metronic/themes/metronic/theme/default/demo8/dist/assets/media/users/300_21.jpg" alt="image">
																												</span>
																										</div>
																										<div class="kt-chat__text kt-bg-light-brand">
																												Hey there, we’re just writing to let you know <br>that you’ve been subscribed to a repository on GitHub.
																										</div>
																								</div>
																						</div>
																			</div>
																		</div>
																		
																		<div class="kt-portlet__foot">
																				<div class="kt-chat__input">
																						<div class="kt-chat__editor">
																								<textarea style="height: 50px" placeholder="Type here..."></textarea>
																						</div>
																						<div class="kt-chat__toolbar">
																								<div class="kt_chat__tools">
																										<a href="#"><i class="flaticon2-link"></i></a>
																										<a href="#"><i class="flaticon2-photograph"></i></a>
																										<a href="#"><i class="flaticon2-photo-camera"></i></a>
																								</div>
																								<div class="kt_chat__actions">
																										<button type="button" class="btn btn-brand btn-md btn-upper btn-bold kt-chat__reply">reply</button>
																								</div>
																						</div>
																				</div>
																		</div>
																</div>
														</div>
												</div>
										</div>
									</div>
									<!---->
								</div>
							</div>
						</div>
					</div>
					<div class="kt-footer	kt-grid__item" id="kt_footer">
						<div class="kt-container	kt-container--fluid ">
							<div class="kt-footer__wrapper">
								<div class="kt-footer__copyright">
									2020&nbsp;&copy;&nbsp;
								</div>
								<div class="kt-footer__menu">
									<a href="/" target="_blank" class="kt-link">About</a>
									<a href="/" target="_blank" class="kt-link">Team</a>
									<a href="/" target="_blank" class="kt-link">Contact</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		{{ assetter.js()|raw }}
		<script type="text/javascript">
			const broadcast = io('http://sockets.qk4req.ru/broadcast', {query: 'auth_token={{ token }}'});
			broadcast.on('connect', function() {
				broadcast.emit('test');
				broadcast.on('ready', () => {
					console.log('READY STREAM!@#!@#!@#');
				});
				broadcast.on('notReady', () => {
					console.log('Not READY STREAM!@#!@#!@#');
				});
			});

			var player = videojs('broadcast', {
				controls: true,
				autoplay: true,
				loop: false,
				preload: 'auto',
				children: {
					mediaLoader: {},
					TextTrackDisplay: {},
					loadingSpinner: {},
					liveTracker: {},
					controlBar: {},
					textTrackSettings: {}
				},
				html5: {
					hlsjsConfig: {
						debug: true,
						autoStartLoad: true
					}
				}
			});
			class Poster extends videojs.getComponent('Component') {
				name () {
					return 'Poster';
				}
				constructor (player, options = {}) {
					var t = super();
					t.addClass('vjs-poster');
					t.addClass('vjs-hidden');
					/*t.on(player, 'error', function(e) {
						var onError = function (ms) {
							var reloading = false;
							if (!reloading) {
								reloading = true;
								player.setTimeout(
									function () {
										player.src(srcObj);
										if (player.error() instanceof Object) {
											if (!t.hasClass('vjs-hidden')) t.show();
										} else {
											reloading = false;
											t.hide();
											t.play();
										}
									}
								, ms);
							}
						}
						onError(5000);
					});*/
				}
			}
			player.addChild(new Poster(player), {name: 'Poster'});
			player.ready(function () {
				var ls = this.getChild('LoadingSpinner'),
					p = this.getChild('Poster');
				//http://qk4req.ru/hls/test.m3u8
				this.tech_.on(Hls.Events.MANIFEST_PARSED, function (event, data) {
					console.log("manifest loaded, found " + data.levels.length + " quality level");
					player.play();
				});
				this.tech_.on(Hls.Events.ERROR, function (event, data) {
					var hls = this.sourceHandler_.hls;
					if (data.fatal) {
						/*if (p.hasClass('vjs-hidden')) {
							ls.hide();
							p.show();
						}*/
						switch(data.type) {
						case Hls.ErrorTypes.NETWORK_ERROR:
						// try to recover network error
							console.log("fatal network error encountered, try to recover");
							hls.startLoad();
							break;
						case Hls.ErrorTypes.MEDIA_ERROR:
							console.log("fatal media error encountered, try to recover");
							hls.recoverMediaError();
							break;
						default:
						// cannot recover
							hls.destroy();
							break;
						}
					}
				});
			})
		</script>

	</body>
</html>